### ISSUE TITLE
Project Topic

### ISSUE THREAD

**Issue by vincentgruse** [vincentgruse/COSC612-IntelliChef#1]
- Choose a project topic, as a team.
- Each project must adhere to the following constraints:
    - The project must be substantial enough to justify a group of seniors working for an entire semester:3K-5K is expected.
    - The project should include some ML/AI components in it.
    - The project must be able to be installed, run, and tested by the instructor.
    - The system must be easy to test; thus, interactive systems are required.

**Comment by Rahal-Kanishka** [comment]
Since we have came to a conclusion for the project topic, Im closing this issue
